# Site settings
title: eddy allen
email: booking@eddyallen.co.uk
url: http://eddyallen.co.uk
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Eddy Allen

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/EddyAllenMusic
  # - title: skype
  #   url: eddyallen4peace
  # - title: twitter
  #   url: 

# Build settings
markdown: kramdown
permalink: pretty
